Only set the comment when persist_docs.relation is set
starburstdata/dbt-trino pull request #344
Opened 2023-08-10 09:06 UTC by Fokko

## Overview

I accidentally changed default behavior in https://github.com/starburstdata/dbt-trino/pull/317

Resolves #343

Checked that it only sets the comment when:

```json
{{ config(
    ...
    persist_docs={"relation": true}
) }}
```

And with the following configuration it won't set the comment:

```json
{{ config(
    ...
    persist_docs={"relation": false}
) }}
```

```json
{{ config(
    ...
) }}
```

## Checklist

- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] `README.md` updated and added information about my change
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/starburstdata/dbt-trino/blob/master/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

2023-08-17 14:41 UTC, Fokko commented
Gentle ping @damian3031

2023-08-25 18:04 UTC, damian3031 requested changes

2023-08-25 18:04 UTC, damian3031 commented on dbt/include/trino/macros/adapters.sql
> +  {%- set persist_docs = model['config'].get('persist_docs', {}) -%}
```suggestion
  {%- set persist_docs = model['config'].get('persist_docs') -%}
```
Here, `get` returns `{}` by default if given key is missing, no need to specify it explicitly

2023-08-25 18:04 UTC, damian3031 commented on dbt/include/trino/macros/adapters.sql
> +  {%- if persist_docs is not none -%}
```suggestion
  {%- if persist_docs -%}
```
We should check if `persist_docs` evaluates to True. Currently it checks if it is not None
(`{}` will pass current condition, but it shouldn't)

2023-08-28 12:01 UTC, damian3031 commented
@Fokko I added tests for this change

2023-09-15 17:57 UTC, damian3031 commented
Gentle ping @Fokko 🙂 Please adjust to (or comment on) the requested changes, and PR is good to merge

2023-09-15 18:40 UTC, Fokko commented
@damian3031 Sorry for not replying earlier, thanks for adding tests, and the changes look good 👍🏻

2023-09-18 09:58 UTC, damian3031 commented
@Fokko thanks! Could you squash these 2 new commits into the first one? (this one [`2432b48` (#344)](https://github.com/starburstdata/dbt-trino/pull/344/commits/2432b48a9a56e309932f51434ed8a33e5c014df1))

2023-09-27 07:40 UTC, damian3031 approved these changes

2023-09-27 07:40 UTC, merged

2023-09-27 07:41 UTC, damian3031 commented
@Fokko thanks for your contribution!

2023-10-05 23:23 UTC, alaturqua commented
@Fokko Thank you for fixing this.

When is the next release actually?

2023-10-10 17:21 UTC, damian3031 commented
@alaturqua It has just been released in 1.6.2!

2023-10-10 17:52 UTC, Fokko commented
Thanks @damian3031 for shepherding this, and sorry @alaturqua for breaking this